window.GGP_EPISODES = window.GGP_EPISODES || {};
window.GGP_EPISODES._registry = [
  {
    id: "ep20",
    number: 20,
    title: "Обучение программированию — юбилейный выпуск",
    date: "2024-11-24",
    duration: "3ч 33м",
    totalWords: 32100,
    totalUtterances: 478,
    totalResources: 38,
    speakerNames: ["Николай Тузов", "Глеб", "Алексей Акулович"],
    speakerColors: ["#6366f1", "#f59e0b", "#10b981"],
    description: "Глеб (PixelStorm) и Алексей Акулович обсуждают стратегии обучения, Go, алгоритмы и книги",
    tags: ["Go", "обучение", "алгоритмы", "книги", "хакатоны"],
  },
  {
    id: "ep21",
    number: 21,
    title: "Обучение программированию — с новыми людьми",
    date: "2025-01-15",
    duration: "2ч 56м",
    totalWords: 12200,
    totalUtterances: 303,
    totalResources: 72,
    speakerNames: ["Николай Тузов", "Кирилл Мокевнин", "Влад Тен"],
    speakerColors: ["#6366f1", "#f59e0b", "#10b981"],
    description: "Кирилл Мокевнин (Hexlet) и Влад обсуждают SICP, A-players, фундаментальное образование и роль ИИ",
    tags: ["образование", "SICP", "Hexlet", "книги", "ИИ"],
  },
];
